<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PortfolioSubKategoriTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('portfolio_sub_kategori')->delete();
        
        \DB::table('portfolio_sub_kategori')->insert(array (
            0 => 
            array (
                'id' => 2,
                'kategori_id' => 11,
                'urutan' => 1,
                'nama' => 'sub logo',
                'slug' => 'sub-logo',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 09:44:05',
                'updated_at' => '2023-05-03 09:44:05',
            ),
            1 => 
            array (
                'id' => 4,
                'kategori_id' => 7,
                'urutan' => 1,
                'nama' => 'Sub ilustrator',
                'slug' => 'sub-ilustrator',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 09:48:48',
                'updated_at' => '2023-05-03 09:48:48',
            ),
            2 => 
            array (
                'id' => 5,
                'kategori_id' => 7,
                'urutan' => 2,
                'nama' => 'ss',
                'slug' => 'ss',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 09:48:53',
                'updated_at' => '2023-05-03 09:48:53',
            ),
            3 => 
            array (
                'id' => 6,
                'kategori_id' => 11,
                'urutan' => 2,
                'nama' => 'logo2',
                'slug' => 'logo2',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 09:49:59',
                'updated_at' => '2023-05-03 09:49:59',
            ),
            4 => 
            array (
                'id' => 50,
                'kategori_id' => 17,
                'urutan' => 1,
                'nama' => 'Banner or Billboard Design',
                'slug' => 'banner-or-billboard-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            5 => 
            array (
                'id' => 51,
                'kategori_id' => 17,
                'urutan' => 2,
                'nama' => 'Poster Design',
                'slug' => 'poster-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            6 => 
            array (
                'id' => 52,
                'kategori_id' => 17,
                'urutan' => 3,
                'nama' => 'Packaging Design',
                'slug' => 'packaging-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            7 => 
            array (
                'id' => 53,
                'kategori_id' => 17,
                'urutan' => 4,
                'nama' => 'Product Design',
                'slug' => 'product-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            8 => 
            array (
                'id' => 54,
                'kategori_id' => 17,
                'urutan' => 5,
                'nama' => 'Signage Design',
                'slug' => 'signage-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            9 => 
            array (
                'id' => 55,
                'kategori_id' => 17,
                'urutan' => 6,
                'nama' => 'Booth Design',
                'slug' => 'booth-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            10 => 
            array (
                'id' => 56,
                'kategori_id' => 17,
                'urutan' => 7,
                'nama' => 'Infographic Design',
                'slug' => 'infographic-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            11 => 
            array (
                'id' => 57,
                'kategori_id' => 17,
                'urutan' => 8,
                'nama' => 'Icon Design',
                'slug' => 'icon-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            12 => 
            array (
                'id' => 58,
                'kategori_id' => 17,
                'urutan' => 9,
                'nama' => 'UI/UX Design',
                'slug' => 'ui-ux-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            13 => 
            array (
                'id' => 59,
                'kategori_id' => 17,
                'urutan' => 10,
                'nama' => 'Social Media Design',
                'slug' => 'social-media-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            14 => 
            array (
                'id' => 60,
                'kategori_id' => 17,
                'urutan' => 11,
                'nama' => 'Logo Design',
                'slug' => 'logo-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            15 => 
            array (
                'id' => 61,
                'kategori_id' => 17,
                'urutan' => 12,
                'nama' => 'Line Sticker',
                'slug' => 'line-sticker',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            16 => 
            array (
                'id' => 62,
                'kategori_id' => 17,
                'urutan' => 13,
                'nama' => 'Vector Design',
                'slug' => 'vector-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            17 => 
            array (
                'id' => 63,
                'kategori_id' => 17,
                'urutan' => 14,
                'nama' => 'AutoCAD Drafter',
                'slug' => 'autocad-drafter',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            18 => 
            array (
                'id' => 64,
                'kategori_id' => 17,
                'urutan' => 15,
                'nama' => 'Graphic Design',
                'slug' => 'graphic-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            19 => 
            array (
                'id' => 65,
                'kategori_id' => 17,
                'urutan' => 16,
                'nama' => 'Invitation Design',
                'slug' => 'invitation-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            20 => 
            array (
                'id' => 66,
                'kategori_id' => 17,
                'urutan' => 17,
                'nama' => 'Web Design',
                'slug' => 'web-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            21 => 
            array (
                'id' => 67,
                'kategori_id' => 17,
                'urutan' => 18,
                'nama' => 'Mobile Apps Design',
                'slug' => 'mobile-apps-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            22 => 
            array (
                'id' => 68,
                'kategori_id' => 17,
                'urutan' => 19,
                'nama' => 'Mascot/Character Design',
                'slug' => 'mascot-character-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            23 => 
            array (
                'id' => 69,
                'kategori_id' => 17,
                'urutan' => 20,
                'nama' => 'Other Design',
                'slug' => 'other-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            24 => 
            array (
                'id' => 70,
                'kategori_id' => 17,
                'urutan' => 21,
                'nama' => 'Image & Illustration ',
                'slug' => 'image-illustration',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            25 => 
            array (
                'id' => 71,
                'kategori_id' => 17,
                'urutan' => 22,
                'nama' => 'Book Design',
                'slug' => 'book-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            26 => 
            array (
                'id' => 72,
                'kategori_id' => 17,
                'urutan' => 23,
                'nama' => 'Landing Page Design',
                'slug' => 'landing-page-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            27 => 
            array (
                'id' => 73,
                'kategori_id' => 17,
                'urutan' => 24,
                'nama' => 'Office Uniform/Clothing Design',
                'slug' => 'office-uniform-clothing-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            28 => 
            array (
                'id' => 74,
                'kategori_id' => 17,
                'urutan' => 25,
                'nama' => 'Calendar Design',
                'slug' => 'calendar-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            29 => 
            array (
                'id' => 75,
                'kategori_id' => 17,
                'urutan' => 26,
                'nama' => 'Image Editing & Photoshop',
                'slug' => 'image-editing-photoshop',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            30 => 
            array (
                'id' => 76,
                'kategori_id' => 17,
                'urutan' => 27,
                'nama' => 'Interior Design',
                'slug' => 'interior-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            31 => 
            array (
                'id' => 77,
                'kategori_id' => 17,
                'urutan' => 28,
                'nama' => 'Cellphone Case Design',
                'slug' => 'cellphone-case-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            32 => 
            array (
                'id' => 78,
                'kategori_id' => 17,
                'urutan' => 29,
                'nama' => 'Menu Design',
                'slug' => 'menu-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            33 => 
            array (
                'id' => 79,
                'kategori_id' => 17,
                'urutan' => 30,
                'nama' => 'Email Design',
                'slug' => 'email-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            34 => 
            array (
                'id' => 80,
                'kategori_id' => 17,
                'urutan' => 31,
                'nama' => 'Label Design',
                'slug' => 'label-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            35 => 
            array (
                'id' => 81,
                'kategori_id' => 17,
                'urutan' => 32,
                'nama' => 'Business Card & Stationery Design',
                'slug' => 'business-card-stationery-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            36 => 
            array (
                'id' => 82,
                'kategori_id' => 17,
                'urutan' => 33,
                'nama' => 'Brochure or Flyer Design',
                'slug' => 'brochure-or-flyer-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            37 => 
            array (
                'id' => 83,
                'kategori_id' => 17,
                'urutan' => 34,
                'nama' => 'Presentation Design',
                'slug' => 'presentation-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            38 => 
            array (
                'id' => 84,
                'kategori_id' => 17,
                'urutan' => 35,
                'nama' => 'Brochure',
                'slug' => 'brochure',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            39 => 
            array (
                'id' => 85,
                'kategori_id' => 17,
                'urutan' => 36,
                'nama' => 'Brand Guidelines',
                'slug' => 'brand-guidelines',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            40 => 
            array (
                'id' => 86,
                'kategori_id' => 17,
                'urutan' => 37,
                'nama' => 'Portrait Image',
                'slug' => 'portrait-image',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            41 => 
            array (
                'id' => 87,
                'kategori_id' => 17,
                'urutan' => 38,
                'nama' => 'Portfolio & Resume Design',
                'slug' => 'portfolio-resume-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            42 => 
            array (
                'id' => 88,
                'kategori_id' => 17,
                'urutan' => 39,
                'nama' => 'Book/Magazine Cover Design',
                'slug' => 'book-magazine-cover-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            43 => 
            array (
                'id' => 89,
                'kategori_id' => 17,
                'urutan' => 40,
                'nama' => '3D & Perspective',
                'slug' => '3d-perspective',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            44 => 
            array (
                'id' => 90,
                'kategori_id' => 17,
                'urutan' => 41,
                'nama' => 'Catalog Design',
                'slug' => 'catalog-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            45 => 
            array (
                'id' => 91,
                'kategori_id' => 17,
                'urutan' => 42,
                'nama' => 'Company Profile Design',
                'slug' => 'company-profile-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            46 => 
            array (
                'id' => 92,
                'kategori_id' => 17,
                'urutan' => 43,
                'nama' => 'Merchandising Design',
                'slug' => 'merchandising-design',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            47 => 
            array (
                'id' => 93,
                'kategori_id' => 17,
                'urutan' => 44,
                'nama' => 'Ecommerce Development',
                'slug' => 'ecommerce-development',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            48 => 
            array (
                'id' => 94,
                'kategori_id' => 16,
                'urutan' => 1,
                'nama' => 'Bug Fixes',
                'slug' => 'bug-fixes',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            49 => 
            array (
                'id' => 95,
                'kategori_id' => 16,
                'urutan' => 2,
                'nama' => 'Other Website & Development Work',
                'slug' => 'other-website-development-work',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            50 => 
            array (
                'id' => 96,
                'kategori_id' => 16,
                'urutan' => 3,
            'nama' => 'Quality Assurance (QA)',
                'slug' => 'quality-assurance-qa',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            51 => 
            array (
                'id' => 97,
                'kategori_id' => 16,
                'urutan' => 4,
                'nama' => 'Slicing to HTML',
                'slug' => 'slicing-to-html',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            52 => 
            array (
                'id' => 98,
                'kategori_id' => 16,
                'urutan' => 5,
                'nama' => 'Mobile App Development for Android',
                'slug' => 'mobile-app-development-for-android',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            53 => 
            array (
                'id' => 99,
                'kategori_id' => 16,
                'urutan' => 6,
                'nama' => 'IT Support',
                'slug' => 'it-support',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            54 => 
            array (
                'id' => 100,
                'kategori_id' => 16,
                'urutan' => 7,
                'nama' => 'Wordpress',
                'slug' => 'wordpress',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            55 => 
            array (
                'id' => 101,
                'kategori_id' => 16,
                'urutan' => 8,
                'nama' => 'Ecommerce Development',
                'slug' => 'ecommerce-development-2',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            56 => 
            array (
                'id' => 102,
                'kategori_id' => 16,
                'urutan' => 9,
                'nama' => 'Mobile Apps',
                'slug' => 'mobile-apps',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            57 => 
            array (
                'id' => 103,
                'kategori_id' => 16,
                'urutan' => 10,
                'nama' => 'Game Development',
                'slug' => 'game-development',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            58 => 
            array (
                'id' => 104,
                'kategori_id' => 16,
                'urutan' => 11,
                'nama' => 'Desktop Application',
                'slug' => 'desktop-application',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            59 => 
            array (
                'id' => 105,
                'kategori_id' => 16,
                'urutan' => 12,
                'nama' => 'Web Programming',
                'slug' => 'web-programming',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            60 => 
            array (
                'id' => 106,
                'kategori_id' => 16,
                'urutan' => 13,
                'nama' => 'Website Maintenance',
                'slug' => 'website-maintenance',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            61 => 
            array (
                'id' => 107,
                'kategori_id' => 16,
                'urutan' => 14,
                'nama' => 'Website Development',
                'slug' => 'website-development',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            62 => 
            array (
                'id' => 108,
                'kategori_id' => 16,
                'urutan' => 15,
                'nama' => 'Aerial Photography',
                'slug' => 'aerial-photography',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            63 => 
            array (
                'id' => 109,
                'kategori_id' => 18,
                'urutan' => 1,
                'nama' => 'Catalog Photography',
                'slug' => 'catalog-photography',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            64 => 
            array (
                'id' => 110,
                'kategori_id' => 18,
                'urutan' => 2,
                'nama' => '2D & Animasi',
                'slug' => '2d-animasi',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            65 => 
            array (
                'id' => 111,
                'kategori_id' => 18,
                'urutan' => 3,
                'nama' => 'Social Media Videos',
                'slug' => 'social-media-videos',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            66 => 
            array (
                'id' => 112,
                'kategori_id' => 18,
                'urutan' => 4,
                'nama' => 'E-commerce Product Videos',
                'slug' => 'e-commerce-product-videos',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            67 => 
            array (
                'id' => 113,
                'kategori_id' => 18,
                'urutan' => 5,
                'nama' => 'Food & Beverage Photography',
                'slug' => 'food-beverage-photography',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            68 => 
            array (
                'id' => 114,
                'kategori_id' => 18,
                'urutan' => 6,
                'nama' => 'Video Ads & Commercials',
                'slug' => 'video-ads-commercials',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            69 => 
            array (
                'id' => 115,
                'kategori_id' => 18,
                'urutan' => 7,
                'nama' => 'Video Production',
                'slug' => 'video-production',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            70 => 
            array (
                'id' => 116,
                'kategori_id' => 18,
                'urutan' => 8,
                'nama' => 'Video Editing',
                'slug' => 'video-editing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            71 => 
            array (
                'id' => 117,
                'kategori_id' => 18,
                'urutan' => 9,
                'nama' => 'Product Photography',
                'slug' => 'product-photography',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            72 => 
            array (
                'id' => 118,
                'kategori_id' => 18,
                'urutan' => 10,
                'nama' => 'Portrait Photography',
                'slug' => 'portrait-photography',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            73 => 
            array (
                'id' => 119,
                'kategori_id' => 18,
                'urutan' => 11,
                'nama' => 'Sound Effects',
                'slug' => 'sound-effects',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            74 => 
            array (
                'id' => 120,
                'kategori_id' => 18,
                'urutan' => 12,
                'nama' => 'Wedding Photography',
                'slug' => 'wedding-photography',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            75 => 
            array (
                'id' => 121,
                'kategori_id' => 18,
                'urutan' => 13,
                'nama' => 'Event Documentation',
                'slug' => 'event-documentation',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            76 => 
            array (
                'id' => 122,
                'kategori_id' => 18,
                'urutan' => 14,
                'nama' => 'Whiteboard & Animated Explainers',
                'slug' => 'whiteboard-animated-explainers',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            77 => 
            array (
                'id' => 123,
                'kategori_id' => 18,
                'urutan' => 15,
                'nama' => 'Real Estate Photography',
                'slug' => 'real-estate-photography',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            78 => 
            array (
                'id' => 124,
                'kategori_id' => 18,
                'urutan' => 16,
                'nama' => 'Photo Editing',
                'slug' => 'photo-editing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            79 => 
            array (
                'id' => 125,
                'kategori_id' => 18,
                'urutan' => 17,
                'nama' => 'Animation for Streamers',
                'slug' => 'animation-for-streamers',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            80 => 
            array (
                'id' => 126,
                'kategori_id' => 18,
                'urutan' => 18,
                'nama' => 'Voice Editing',
                'slug' => 'voice-editing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            81 => 
            array (
                'id' => 127,
                'kategori_id' => 18,
                'urutan' => 19,
                'nama' => 'Unboxing Videos',
                'slug' => 'unboxing-videos',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            82 => 
            array (
                'id' => 128,
                'kategori_id' => 18,
                'urutan' => 20,
                'nama' => 'Voice Over',
                'slug' => 'voice-over',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            83 => 
            array (
                'id' => 129,
                'kategori_id' => 18,
                'urutan' => 21,
                'nama' => 'Lifestyle & Fashion Photography',
                'slug' => 'lifestyle-fashion-photography',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            84 => 
            array (
                'id' => 130,
                'kategori_id' => 18,
                'urutan' => 22,
                'nama' => 'Other Video, Photography, Audio',
                'slug' => 'other-video-photography-audio',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            85 => 
            array (
                'id' => 131,
                'kategori_id' => 18,
                'urutan' => 23,
                'nama' => 'Corporate Videos',
                'slug' => 'corporate-videos',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            86 => 
            array (
                'id' => 132,
                'kategori_id' => 18,
                'urutan' => 24,
                'nama' => 'Subtitle',
                'slug' => 'subtitle',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            87 => 
            array (
                'id' => 133,
                'kategori_id' => 18,
                'urutan' => 25,
                'nama' => 'Visual Effects',
                'slug' => 'visual-effects',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            88 => 
            array (
                'id' => 134,
                'kategori_id' => 18,
                'urutan' => 26,
                'nama' => '3D & Animation',
                'slug' => '3d-animation',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            89 => 
            array (
                'id' => 135,
                'kategori_id' => 18,
                'urutan' => 27,
                'nama' => 'Motion Graphics',
                'slug' => 'motion-graphics',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            90 => 
            array (
                'id' => 136,
                'kategori_id' => 18,
                'urutan' => 28,
                'nama' => 'Website Content',
                'slug' => 'website-content',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            91 => 
            array (
                'id' => 137,
                'kategori_id' => 19,
                'urutan' => 1,
                'nama' => 'Articles & Blog Posts',
                'slug' => 'articles-blog-posts',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            92 => 
            array (
                'id' => 138,
                'kategori_id' => 19,
                'urutan' => 2,
            'nama' => 'Product Description Writing (Bahasa)',
                'slug' => 'product-description-writing-bahasa',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            93 => 
            array (
                'id' => 139,
                'kategori_id' => 19,
                'urutan' => 3,
                'nama' => 'Book & eBook Writing',
                'slug' => 'book-ebook-writing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            94 => 
            array (
                'id' => 140,
                'kategori_id' => 19,
                'urutan' => 4,
                'nama' => 'Resume Writing',
                'slug' => 'resume-writing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            95 => 
            array (
                'id' => 141,
                'kategori_id' => 19,
                'urutan' => 5,
                'nama' => 'Sales Copy',
                'slug' => 'sales-copy',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            96 => 
            array (
                'id' => 142,
                'kategori_id' => 19,
                'urutan' => 6,
                'nama' => 'Creative Writing',
                'slug' => 'creative-writing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            97 => 
            array (
                'id' => 143,
                'kategori_id' => 19,
                'urutan' => 7,
                'nama' => 'Ads Copy',
                'slug' => 'ads-copy',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            98 => 
            array (
                'id' => 144,
                'kategori_id' => 19,
                'urutan' => 8,
                'nama' => 'Translation',
                'slug' => 'translation',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            99 => 
            array (
                'id' => 145,
                'kategori_id' => 19,
                'urutan' => 9,
                'nama' => 'Proofreading & Editing',
                'slug' => 'proofreading-editing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            100 => 
            array (
                'id' => 146,
                'kategori_id' => 19,
                'urutan' => 10,
                'nama' => 'Other Writing, Translations, Data Entry',
                'slug' => 'other-writing-translations-data-entry',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            101 => 
            array (
                'id' => 147,
                'kategori_id' => 19,
                'urutan' => 11,
                'nama' => 'Research & Summaries',
                'slug' => 'research-summaries',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            102 => 
            array (
                'id' => 148,
                'kategori_id' => 19,
                'urutan' => 12,
                'nama' => 'Business Names & Slogans',
                'slug' => 'business-names-slogans',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            103 => 
            array (
                'id' => 149,
                'kategori_id' => 19,
                'urutan' => 13,
                'nama' => 'Technical Writing',
                'slug' => 'technical-writing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            104 => 
            array (
                'id' => 150,
                'kategori_id' => 19,
                'urutan' => 14,
                'nama' => 'Data Entry in Excel',
                'slug' => 'data-entry-in-excel',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            105 => 
            array (
                'id' => 151,
                'kategori_id' => 19,
                'urutan' => 15,
                'nama' => 'Email Copy',
                'slug' => 'email-copy',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            106 => 
            array (
                'id' => 152,
                'kategori_id' => 19,
                'urutan' => 16,
                'nama' => 'Social Media Copy',
                'slug' => 'social-media-copy',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            107 => 
            array (
                'id' => 153,
                'kategori_id' => 19,
                'urutan' => 17,
                'nama' => 'Data Entry in Website',
                'slug' => 'data-entry-in-website',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            108 => 
            array (
                'id' => 154,
                'kategori_id' => 19,
                'urutan' => 18,
                'nama' => 'Podcast Writing',
                'slug' => 'podcast-writing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            109 => 
            array (
                'id' => 155,
                'kategori_id' => 19,
                'urutan' => 19,
                'nama' => 'Press Releases',
                'slug' => 'press-releases',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            110 => 
            array (
                'id' => 156,
                'kategori_id' => 19,
                'urutan' => 20,
                'nama' => 'Case Studies',
                'slug' => 'case-studies',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            111 => 
            array (
                'id' => 157,
                'kategori_id' => 19,
                'urutan' => 21,
                'nama' => 'Scriptwriting',
                'slug' => 'scriptwriting',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            112 => 
            array (
                'id' => 158,
                'kategori_id' => 19,
                'urutan' => 22,
                'nama' => 'Job Descriptions',
                'slug' => 'job-descriptions',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            113 => 
            array (
                'id' => 159,
                'kategori_id' => 19,
                'urutan' => 23,
                'nama' => 'Speechwriting',
                'slug' => 'speechwriting',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            114 => 
            array (
                'id' => 160,
                'kategori_id' => 19,
                'urutan' => 24,
                'nama' => 'Product Description',
                'slug' => 'product-description',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            115 => 
            array (
                'id' => 161,
                'kategori_id' => 19,
                'urutan' => 25,
                'nama' => 'Web Traffic & Analytics',
                'slug' => 'web-traffic-analytics',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            116 => 
            array (
                'id' => 162,
                'kategori_id' => 20,
                'urutan' => 1,
                'nama' => 'Mobile App Marketing',
                'slug' => 'mobile-app-marketing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            117 => 
            array (
                'id' => 163,
                'kategori_id' => 20,
                'urutan' => 2,
                'nama' => 'Youtube Marketing',
                'slug' => 'youtube-marketing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            118 => 
            array (
                'id' => 164,
                'kategori_id' => 20,
                'urutan' => 3,
                'nama' => 'Blogger Marketing',
                'slug' => 'blogger-marketing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            119 => 
            array (
                'id' => 165,
                'kategori_id' => 20,
                'urutan' => 4,
                'nama' => 'Social Media Marketing',
                'slug' => 'social-media-marketing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            120 => 
            array (
                'id' => 166,
                'kategori_id' => 20,
                'urutan' => 5,
                'nama' => 'Market Research',
                'slug' => 'market-research',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            121 => 
            array (
                'id' => 167,
                'kategori_id' => 20,
                'urutan' => 6,
                'nama' => 'Other Online Marketing Work',
                'slug' => 'other-online-marketing-work',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            122 => 
            array (
                'id' => 168,
                'kategori_id' => 20,
                'urutan' => 7,
                'nama' => 'Affiliate Marketing',
                'slug' => 'affiliate-marketing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            123 => 
            array (
                'id' => 169,
                'kategori_id' => 20,
                'urutan' => 8,
                'nama' => 'Buzzer Marketing',
                'slug' => 'buzzer-marketing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            124 => 
            array (
                'id' => 170,
                'kategori_id' => 20,
                'urutan' => 9,
                'nama' => 'Add Social Media Followers',
                'slug' => 'add-social-media-followers',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            125 => 
            array (
                'id' => 171,
                'kategori_id' => 20,
                'urutan' => 10,
                'nama' => 'Add Reviews',
                'slug' => 'add-reviews',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            126 => 
            array (
                'id' => 172,
                'kategori_id' => 20,
                'urutan' => 11,
            'nama' => 'Search Engine Marketing (SEM)',
                'slug' => 'search-engine-marketing-sem',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            127 => 
            array (
                'id' => 173,
                'kategori_id' => 20,
                'urutan' => 12,
                'nama' => 'Public Relation',
                'slug' => 'public-relation',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            128 => 
            array (
                'id' => 174,
                'kategori_id' => 20,
                'urutan' => 13,
                'nama' => 'Video Marketing',
                'slug' => 'video-marketing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            129 => 
            array (
                'id' => 175,
                'kategori_id' => 20,
                'urutan' => 14,
                'nama' => 'Ecommerce Marketing',
                'slug' => 'ecommerce-marketing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            130 => 
            array (
                'id' => 176,
                'kategori_id' => 20,
                'urutan' => 15,
                'nama' => 'Paid ads - Instagram',
                'slug' => 'paid-ads-instagram',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            131 => 
            array (
                'id' => 177,
                'kategori_id' => 20,
                'urutan' => 16,
                'nama' => 'Book & eBook Marketing',
                'slug' => 'book-ebook-marketing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            132 => 
            array (
                'id' => 178,
                'kategori_id' => 20,
                'urutan' => 17,
                'nama' => 'Beauty Product Reviews',
                'slug' => 'beauty-product-reviews',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            133 => 
            array (
                'id' => 179,
                'kategori_id' => 20,
                'urutan' => 18,
                'nama' => 'Email Marketing',
                'slug' => 'email-marketing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            134 => 
            array (
                'id' => 180,
                'kategori_id' => 20,
                'urutan' => 19,
                'nama' => 'Create IG Reels',
                'slug' => 'create-ig-reels',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            135 => 
            array (
                'id' => 181,
                'kategori_id' => 20,
                'urutan' => 20,
            'nama' => 'Influencer Marketing (Selebgram)',
                'slug' => 'influencer-marketing-selebgram',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            136 => 
            array (
                'id' => 182,
                'kategori_id' => 20,
                'urutan' => 21,
                'nama' => 'Online Store Product Updates',
                'slug' => 'online-store-product-updates',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            137 => 
            array (
                'id' => 183,
                'kategori_id' => 20,
                'urutan' => 22,
                'nama' => 'Tiktok Live Marketing',
                'slug' => 'tiktok-live-marketing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            138 => 
            array (
                'id' => 184,
                'kategori_id' => 20,
                'urutan' => 23,
            'nama' => 'SEO (Search Engine Optimization)',
                'slug' => 'seo-search-engine-optimization',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            139 => 
            array (
                'id' => 185,
                'kategori_id' => 20,
                'urutan' => 24,
                'nama' => 'Backlink PBN',
                'slug' => 'backlink-pbn',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            140 => 
            array (
                'id' => 186,
                'kategori_id' => 20,
                'urutan' => 25,
                'nama' => 'Podcast Marketing',
                'slug' => 'podcast-marketing',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            141 => 
            array (
                'id' => 187,
                'kategori_id' => 20,
                'urutan' => 26,
                'nama' => 'Paid ads - Facebook',
                'slug' => 'paid-ads-facebook',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
            142 => 
            array (
                'id' => 188,
                'kategori_id' => 20,
                'urutan' => 27,
                'nama' => 'Guest Posting',
                'slug' => 'guest-posting',
                'keterangan' => NULL,
                'created_at' => '2023-05-03 21:54:54',
                'updated_at' => '2023-05-03 21:54:54',
            ),
        ));
        
        
    }
}